#!/usr/bin/python3
import sys
argv = sys.argv[1]
file1 = open(argv, 'r')
lines = file1.readlines()
for line in lines:
    num = int(line)
    i = 2
    while i <= num:
        div = int (num / i)
        if (num % i == 0):
            print ('{}={}*{}'.format(num, div, i))
            break
        else:
            i += 1



